stages:
  - publish

github-mirror:
  stage: publish
  script:
    - setsid ./ci/github-mirror.sh
  only:
    - /^(master.*)$/
  tags:
    - elasticlifecycle

elastalert-arm:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "arm" "elastalert" "1.0"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - elastalert/*
  tags:
    - buildarm

elasticsearch-arm:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "arm" "elasticsearch" "7.10.2" "1.0"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - elasticsearch/*
  tags:
    - buildarm

kibana-arm:
  stage: publish
  script:
    - setsid ./ci/docker-deliver.sh "arm" "kibana" "7.10.2" "1.2"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - kibana/*
  tags:
    - buildarm
