version: "3.3"

services:
  elasticsearch:
    image: comworkio/elasticsearch
    build:
      context: elasticsearch
      dockerfile: Dockerfile
  elastalert:
    image: comworkio/elastalert
    build:
      context: elastalert
      dockerfile: Dockerfile
  kibana:
    image: comworkio/kibana
    build:
      context: kibana
      dockerfile: Dockerfile
